### ISSUE TITLE
Distribution through CocoaPods

### ISSUE THREAD

**Issue by fastred** [fastred/IBAnalyzer#14]
Should be similar to [SwiftGen](https://github.com/AliSoftware/SwiftGen#installation) or [Sourcery](https://github.com/krzysztofzablocki/Sourcery).

**Comment by fastred** [comment]
I started the work on this on `feature/cocoapods` branch. Will merge when #23 is ready.

**Comment by fastred** [comment]
This is now fixed on `master`.

**Comment by elneruda** [comment]
On build phase integration (README.md) you should indicate following script: 
`$PODS_ROOT/IBAnalyzer/bin/ibanalyzer` `${SRCROOT}`
instead of
`$PODS_ROOT/IBAnalyzer/bin/ibanalyzer FolderWithSwiftAndNibFiles/`

**Comment by fastred** [comment]
@elneruda Since this is a relative path what I wrote is the same as:

```
$PODS_ROOT/IBAnalyzer/bin/ibanalyzer "${SRCROOT}/FolderWithSwiftAndNibFiles/"
```

My intention was to suggest users to provide path only to their own files, not including external dependencies (like `Pods/` folder).

**Comment by elneruda** [comment]
sure, at this step it will be interesting to support configuration file like swiftlint or taylor : 

for example: `.ibanalyzer.yml`

**Comment by fastred** [comment]
Yes, that would be nice! We could handle https://github.com/fastred/IBAnalyzer/issues/24 this way too.
