### ISSUE TITLE
Relative paths aren't working

### ISSUE THREAD

**Issue by troya2** [fastred/IBAnalyzer#18]
I installed this in ~/bin so I could access it from any project.  However, when launching it, it complains that it cannot find the file. 

e.g.

`ibanalyzer MyProject` results in `Path /Users/troy/bin/IBAnalyzer.app/Contents/MyProject doesn't exist.`

However, launching it like `ibanalyzer ~/Projects/MyProject` works.

**Comment by RobertGummesson** [comment]
I had the same problem.

**Comment by fastred** [comment]
Thanks for reporting! This should be fixed on `master` and in `0.1.1`.
