### ISSUE TITLE
Decide on a distribution model

### ISSUE THREAD

**Issue by fastred** [fastred/IBAnalyzer#3]
Building the project from scratch to be able to use it is cumbersome. We should come up with a better way to distribute it, e.g. by [building a binary the way SwiftGen does](https://github.com/AliSoftware/SwiftGen/blob/master/Rakefile).

**Comment by postmechanical** [comment]
Would love to see it installable via homebrew.

**Comment by ldiqual** [comment]
A `pod` installation would be absolutely great since you could do version pinning. Installing would be as simple as adding `pod IBAnalyzer` in your podfile.

**Comment by fastred** [comment]
@postmechanical @ldiqual Thanks, that's what I was thinking too! I'm closing this ticket in favor of https://github.com/fastred/IBAnalyzer/issues/13, https://github.com/fastred/IBAnalyzer/issues/14 and https://github.com/fastred/IBAnalyzer/issues/15.
