### ISSUE TITLE
IBAnalyzer Installed from cocoapods not working

### ISSUE THREAD

**Issue by bonyadmitr** [fastred/IBAnalyzer#36]
I Installed IBAnalyzer from cocoapods and it is working oppositely.

Example:
Added line
@IBOutlet private weak var someLabel: UILabel!

There is no any warning.
Connected UILabel to this IBOutlet
And appeared warning
/Users/.../XcodeProjects/ScriptsTest/ScriptsTest/Base.lproj/Main.storyboard:37:94: warning: IBOutlet missing: someLabel is not implemented in Main.storyboard

But I compiled sources and replaced IBAnalyzer.app in cocoapods folder and it works correctly.

**Comment by sherc91** [comment]
Same here...

**Comment by mxcl** [comment]
This is fixed in April, but the maintainer has not updated the release binary (since Feb).

**Comment by fastred** [comment]
Sorry for the delay. Just released the binary and updated the pod.
