### ISSUE TITLE
SwiftLint integration

### ISSUE THREAD

**Issue by wokalski** [fastred/IBAnalyzer#7]
I don't use neither IBAnalyzer nor SwiftLint but I guess it would be marvellous to be able to lint for something like this. It might not make sense though so feel free to close.

**Comment by ldrr** [comment]
+1

**Comment by ldiqual** [comment]
While it seems neat, I'm not sure it is the role of a swift linter to lint iOS/OSX related assets. SwiftLint is purely for making sure that your swift code is properly styled while covering stuff like "don't use optional force unwrapping", but IBs are part of a bigger environment that swift is barely related with. Swift also runs on linux, android, and there's a big push for backend server in swift, all of those unrelated to IBs.

**Comment by fastred** [comment]
I tend to agree with @ldiqual here. One more reason is that SwiftLint operates on a file-by-file basis whereas IBAnalyzer requires knowledge about all Swift types in the project (at least for the currently implemented warnings).

IBAnalyzer is in a super-early phase of life. Ideally I'd like it to be distributed through CocoaPods or Homebrew and emit warnings visible in the Issue navigator, similarly to SwiftLint.

I'm going to close this issue for now. Feel free to reopen.

**Comment by wokalski** [comment]
sure, I was aware that it might not make sense. what bothers me though - is there no tool to rule them all when it comes to linting iOS projects?
