### ISSUE TITLE
Support @IBAction in extension

### ISSUE THREAD

**Issue by ethanhuang13** [fastred/IBAnalyzer#9]
`@IBAction func` can be used in extension. I think IBAnalyzer should check if the missing implementation is in an extension.

**Comment by fastred** [comment]
This should work in simple cases like:  https://github.com/fastred/IBAnalyzer/blob/master/IBAnalyzerTests/SwiftParserTests.swift#L53-L58. Would you be able to share your Swift code that IBAnalyzer fails on?

**Comment by ethanhuang13** [comment]
My extension is in another file. Will it still pass?

**Comment by fastred** [comment]
Yeah, it should. Can you copy paste the declaration of your method? (e.g. `@IBAction func didTapButton(_ sender: UIButton) {`)

**Comment by elneruda** [comment]
@ethanhuang13 this feature have been implemented, you can try it with the latest release ?

**Comment by ethanhuang13** [comment]
Tested and it works! Thanks. 
However I have some other suggestion in output wording. Will open another issue.
